"""
[SCH-04] Catálogo completo de controles evaluables por la suite.
Fuente: CIS AWS Foundations Benchmark v1.4 + AWS WAF Security Pillar.
"""

CONTROLS_CATALOG = [
    # ── IAM ───────────────────────────────────────────────────────────────────
    {"control_id": "CIS-IAM-1.4",  "service": "iam", "framework": "CIS", "name_en": "Root account has no active access keys",                    "name_es": "Cuenta root sin access keys activas"},
    {"control_id": "CIS-IAM-1.5",  "service": "iam", "framework": "CIS", "name_en": "Root account MFA enabled",                                  "name_es": "MFA habilitado en cuenta root"},
    {"control_id": "CIS-IAM-1.6",  "service": "iam", "framework": "CIS", "name_en": "Root account uses hardware MFA",                            "name_es": "Root usa MFA de hardware"},
    {"control_id": "CIS-IAM-1.8",  "service": "iam", "framework": "CIS", "name_en": "Password minimum length >= 14",                             "name_es": "Contraseña mínimo 14 caracteres"},
    {"control_id": "CIS-IAM-1.9",  "service": "iam", "framework": "CIS", "name_en": "Password requires uppercase letters",                       "name_es": "Contraseña requiere mayúsculas"},
    {"control_id": "CIS-IAM-1.10", "service": "iam", "framework": "CIS", "name_en": "MFA enabled for all IAM users with console access",         "name_es": "MFA habilitado para todos los usuarios con acceso a consola"},
    {"control_id": "CIS-IAM-1.11", "service": "iam", "framework": "CIS", "name_en": "Password requires symbols",                                 "name_es": "Contraseña requiere símbolos"},
    {"control_id": "CIS-IAM-1.12", "service": "iam", "framework": "CIS", "name_en": "Password requires numbers",                                 "name_es": "Contraseña requiere números"},
    {"control_id": "CIS-IAM-1.13", "service": "iam", "framework": "CIS", "name_en": "Password expiry <= 90 days",                                "name_es": "Contraseña expira en máximo 90 días"},
    {"control_id": "CIS-IAM-1.14", "service": "iam", "framework": "CIS", "name_en": "Access keys rotated within 90 days",                       "name_es": "Access keys rotadas en 90 días"},
    {"control_id": "CIS-IAM-1.15", "service": "iam", "framework": "CIS", "name_en": "IAM policies attached only via groups",                     "name_es": "Políticas IAM solo adjuntas vía grupos"},
    {"control_id": "CIS-IAM-1.16", "service": "iam", "framework": "CIS", "name_en": "No IAM policies with full admin permissions",               "name_es": "Sin políticas IAM con permisos de admin completo"},
    {"control_id": "CIS-IAM-1.17", "service": "iam", "framework": "CIS", "name_en": "Support role created for incident management",              "name_es": "Rol de soporte creado para gestión de incidentes"},
    {"control_id": "CIS-IAM-1.20", "service": "iam", "framework": "CIS", "name_en": "IAM Access Analyzer enabled",                              "name_es": "IAM Access Analyzer habilitado"},
    {"control_id": "WAF-IAM-G01",  "service": "iam", "framework": "WAF", "name_en": "IAM groups are not empty",                                  "name_es": "Grupos IAM no están vacíos"},
    # ── S3 ────────────────────────────────────────────────────────────────────
    {"control_id": "CIS-S3-2.1.2",     "service": "s3", "framework": "CIS", "name_en": "S3 account-level Block Public Access enabled",           "name_es": "Block Public Access habilitado a nivel de cuenta"},
    {"control_id": "CIS-S3-2.1.1",     "service": "s3", "framework": "CIS", "name_en": "S3 bucket Block Public Access enabled",                  "name_es": "Block Public Access habilitado por bucket"},
    {"control_id": "CIS-S3-2.1.3",     "service": "s3", "framework": "CIS", "name_en": "S3 bucket ACL not public",                              "name_es": "ACL del bucket S3 no es pública"},
    {"control_id": "CIS-S3-2.1.4",     "service": "s3", "framework": "CIS", "name_en": "S3 bucket policy not public",                           "name_es": "Política del bucket S3 no es pública"},
    {"control_id": "WAF-S3-ENC-CMK-01","service": "s3", "framework": "WAF", "name_en": "S3 bucket uses KMS CMK for server-side encryption",      "name_es": "Bucket S3 usa KMS CMK para encriptación"},
    {"control_id": "CIS-S3-2.6",       "service": "s3", "framework": "CIS", "name_en": "S3 bucket access logging enabled",                      "name_es": "Access logging habilitado en bucket S3"},
    {"control_id": "WAF-S3-VER-01",    "service": "s3", "framework": "WAF", "name_en": "S3 bucket versioning enabled",                          "name_es": "Versionado habilitado en bucket S3"},
    {"control_id": "WAF-S3-REP-01",    "service": "s3", "framework": "WAF", "name_en": "S3 bucket replication configured",                      "name_es": "Replicación configurada en bucket S3"},
    {"control_id": "WAF-S3-LCY-01",    "service": "s3", "framework": "WAF", "name_en": "S3 bucket lifecycle policy configured",                 "name_es": "Política de ciclo de vida configurada en bucket S3"},
    {"control_id": "WAF-S3-OBL-01",    "service": "s3", "framework": "WAF", "name_en": "S3 bucket object lock configured",                      "name_es": "Object Lock configurado en bucket S3"},
    {"control_id": "WAF-S3-SSL-01",    "service": "s3", "framework": "WAF", "name_en": "S3 bucket enforces SSL-only access",                    "name_es": "Bucket S3 fuerza acceso solo HTTPS"},
    {"control_id": "WAF-S3-WEB-01",    "service": "s3", "framework": "WAF", "name_en": "S3 bucket static website hosting reviewed",             "name_es": "Website estático en bucket S3 revisado"},
    # ── EC2 ───────────────────────────────────────────────────────────────────
    {"control_id": "CIS-EC2-2.2.1",     "service": "ec2", "framework": "CIS", "name_en": "EBS encryption by default enabled",                   "name_es": "Encriptación EBS por defecto habilitada"},
    {"control_id": "CIS-EC2-2.2.1-VOL", "service": "ec2", "framework": "CIS", "name_en": "EBS volumes encrypted at rest",                      "name_es": "Volúmenes EBS encriptados en reposo"},
    {"control_id": "CIS-EC2-2.2.2",     "service": "ec2", "framework": "CIS", "name_en": "EBS snapshots not publicly restorable",              "name_es": "Snapshots EBS no restaurables públicamente"},
    {"control_id": "WAF-EC2-AMI-01",    "service": "ec2", "framework": "WAF", "name_en": "Custom AMIs not public",                             "name_es": "AMIs propias no públicas"},
    {"control_id": "CIS-EC2-5.6",       "service": "ec2", "framework": "CIS", "name_en": "IMDSv2 enforced on EC2 instances",                   "name_es": "IMDSv2 requerido en instancias EC2"},
    {"control_id": "CIS-EC2-5.2",       "service": "ec2", "framework": "CIS", "name_en": "Security groups restrict open ingress",              "name_es": "Security groups sin ingreso abierto en puertos sensibles"},
    {"control_id": "CIS-EC2-5.4",       "service": "ec2", "framework": "CIS", "name_en": "Default security group has no rules",                "name_es": "Security group default sin reglas"},
    {"control_id": "CIS-EC2-3.9",       "service": "ec2", "framework": "CIS", "name_en": "VPC Flow Logs enabled",                              "name_es": "VPC Flow Logs habilitados"},
    {"control_id": "WAF-EC2-MON-01",    "service": "ec2", "framework": "WAF", "name_en": "EC2 instances have detailed monitoring enabled",     "name_es": "Instancias EC2 con monitoring detallado habilitado"},
    {"control_id": "WAF-EC2-PIP-01",    "service": "ec2", "framework": "WAF", "name_en": "EC2 instances without direct public IP",             "name_es": "Instancias EC2 sin IP pública directa"},
    {"control_id": "WAF-EC2-SSM-01",    "service": "ec2", "framework": "WAF", "name_en": "EC2 instances managed by SSM",                      "name_es": "Instancias EC2 gestionadas por SSM"},
    {"control_id": "WAF-EC2-VPE-01",    "service": "ec2", "framework": "WAF", "name_en": "Critical services have VPC Endpoints",              "name_es": "Servicios críticos con VPC Endpoints"},
    {"control_id": "WAF-EC2-SUB-01",    "service": "ec2", "framework": "WAF", "name_en": "Subnets do not auto-assign public IPs",             "name_es": "Subnets sin auto-asignación de IPs públicas"},
    {"control_id": "CIS-EC2-5.1",       "service": "ec2", "framework": "CIS", "name_en": "Network ACLs restrict open ingress on admin ports", "name_es": "NACLs sin ingreso abierto en puertos admin"},
    {"control_id": "WAF-EC2-EIP-01",    "service": "ec2", "framework": "WAF", "name_en": "Elastic IPs are assigned",                          "name_es": "Elastic IPs asignadas (sin huérfanas)"},
    {"control_id": "WAF-EC2-EXP-01",    "service": "ec2", "framework": "WAF", "name_en": "EC2 instances exposure classification",             "name_es": "Clasificación de exposición de instancias EC2"},
    # ── RDS ───────────────────────────────────────────────────────────────────
    {"control_id": "CIS-RDS-2.3.2",         "service": "rds", "framework": "CIS", "name_en": "RDS instances not publicly accessible",              "name_es": "Instancias RDS no accesibles públicamente"},
    {"control_id": "CIS-RDS-2.3.1",         "service": "rds", "framework": "CIS", "name_en": "RDS instances encrypted at rest",                    "name_es": "Instancias RDS encriptadas en reposo"},
    {"control_id": "WAF-RDS-MAZ-01",        "service": "rds", "framework": "WAF", "name_en": "RDS instances have Multi-AZ enabled",               "name_es": "Instancias RDS con Multi-AZ habilitado"},
    {"control_id": "CIS-RDS-2.3.1-BCK",     "service": "rds", "framework": "CIS", "name_en": "RDS instances backup retention >= 7 days",           "name_es": "Retención de backup RDS >= 7 días"},
    {"control_id": "WAF-RDS-DEL-01",        "service": "rds", "framework": "WAF", "name_en": "RDS instances have deletion protection enabled",     "name_es": "Instancias RDS con deletion protection habilitado"},
    {"control_id": "WAF-RDS-IAM-01",        "service": "rds", "framework": "WAF", "name_en": "RDS instances have IAM database authentication",     "name_es": "Instancias RDS con autenticación IAM habilitada"},
    {"control_id": "CIS-RDS-2.3.1-LOG",     "service": "rds", "framework": "CIS", "name_en": "RDS instances have required CloudWatch logs enabled", "name_es": "Logs requeridos de RDS habilitados en CloudWatch"},
    {"control_id": "WAF-RDS-UPG-01",        "service": "rds", "framework": "WAF", "name_en": "RDS instances have auto minor version upgrade",      "name_es": "Instancias RDS con auto minor version upgrade"},
    {"control_id": "WAF-RDS-PI-01",         "service": "rds", "framework": "WAF", "name_en": "RDS instances have Performance Insights enabled",    "name_es": "Instancias RDS con Performance Insights habilitado"},
    {"control_id": "CIS-RDS-2.3.3",         "service": "rds", "framework": "CIS", "name_en": "RDS snapshots not publicly accessible",              "name_es": "Snapshots RDS no accesibles públicamente"},
    {"control_id": "CIS-RDS-2.3.3-CLU",     "service": "rds", "framework": "CIS", "name_en": "RDS cluster snapshots not publicly accessible",      "name_es": "Snapshots de clusters RDS no accesibles públicamente"},
    {"control_id": "CIS-RDS-2.3.1-CLU",     "service": "rds", "framework": "CIS", "name_en": "Aurora clusters encrypted at rest",                  "name_es": "Clusters Aurora encriptados en reposo"},
    {"control_id": "CIS-RDS-2.3.1-CLU-BCK", "service": "rds", "framework": "CIS", "name_en": "Aurora clusters backup retention >= 7 days",         "name_es": "Retención de backup de clusters Aurora >= 7 días"},
    {"control_id": "WAF-RDS-CLU-DEL-01",    "service": "rds", "framework": "WAF", "name_en": "Aurora clusters have deletion protection enabled",    "name_es": "Clusters Aurora con deletion protection habilitado"},
    {"control_id": "CIS-RDS-2.3.1-CLU-LOG", "service": "rds", "framework": "CIS", "name_en": "Aurora clusters have required CloudWatch logs",      "name_es": "Logs requeridos de clusters Aurora en CloudWatch"},
    {"control_id": "WAF-RDS-SSL-01",        "service": "rds", "framework": "WAF", "name_en": "RDS parameter groups enforce SSL connections",        "name_es": "Parameter groups de RDS fuerzan SSL"},
    {"control_id": "WAF-RDS-EVT-01",        "service": "rds", "framework": "WAF", "name_en": "RDS event subscriptions configured for critical events","name_es": "Suscripciones a eventos críticos de RDS configuradas"},
    # ── GuardDuty ─────────────────────────────────────────────────────────────
    {"control_id": "CIS-GD-3.1",          "service": "guardduty", "framework": "CIS", "name_en": "GuardDuty enabled in region",                        "name_es": "GuardDuty habilitado en la región"},
    {"control_id": "WAF-GD-EXP-01",       "service": "guardduty", "framework": "WAF", "name_en": "GuardDuty findings export configured",              "name_es": "Exportación de findings de GuardDuty configurada"},
    {"control_id": "WAF-GD-ORG-01",       "service": "guardduty", "framework": "WAF", "name_en": "GuardDuty centralized via AWS Organizations",       "name_es": "GuardDuty centralizado via AWS Organizations"},
    {"control_id": "WAF-GD-PPL-01-S3D",   "service": "guardduty", "framework": "WAF", "name_en": "GuardDuty S3 Protection enabled",                   "name_es": "GuardDuty S3 Protection habilitado"},
    {"control_id": "WAF-GD-PPL-01-EBS",   "service": "guardduty", "framework": "WAF", "name_en": "GuardDuty Malware Protection enabled",              "name_es": "GuardDuty Malware Protection habilitado"},
    {"control_id": "WAF-GD-PPL-01-RUN",   "service": "guardduty", "framework": "WAF", "name_en": "GuardDuty Runtime Monitoring enabled",              "name_es": "GuardDuty Runtime Monitoring habilitado"},
    {"control_id": "WAF-GD-PPL-01-EKS",   "service": "guardduty", "framework": "WAF", "name_en": "GuardDuty EKS Protection enabled",                  "name_es": "GuardDuty EKS Protection habilitado"},
    {"control_id": "WAF-GD-PPL-01-RDS",   "service": "guardduty", "framework": "WAF", "name_en": "GuardDuty RDS Protection enabled",                  "name_es": "GuardDuty RDS Protection habilitado"},
    {"control_id": "WAF-GD-PPL-01-LAM",   "service": "guardduty", "framework": "WAF", "name_en": "GuardDuty Lambda Protection enabled",               "name_es": "GuardDuty Lambda Protection habilitado"},
    {"control_id": "WAF-GD-FND-01",       "service": "guardduty", "framework": "WAF", "name_en": "No active GuardDuty findings with CRITICAL severity","name_es": "Sin findings activos CRITICAL en GuardDuty"},
    {"control_id": "WAF-GD-FND-02",       "service": "guardduty", "framework": "WAF", "name_en": "No active GuardDuty findings with HIGH severity",    "name_es": "Sin findings activos HIGH en GuardDuty"},
    {"control_id": "WAF-GD-TIS-01",       "service": "guardduty", "framework": "WAF", "name_en": "GuardDuty threat intel sets configured",             "name_es": "Threat intel sets de GuardDuty configurados"},
    {"control_id": "WAF-GD-FRQ-01",       "service": "guardduty", "framework": "WAF", "name_en": "GuardDuty finding publish frequency is optimal",    "name_es": "Frecuencia de publicación de GuardDuty óptima"},
    # ── CloudWatch ────────────────────────────────────────────────────────────
    {"control_id": "CIS-CT-3.1",    "service": "cloudwatch", "framework": "CIS", "name_en": "CloudTrail enabled and logging",                         "name_es": "CloudTrail habilitado y activo"},
    {"control_id": "CIS-CT-3.4",    "service": "cloudwatch", "framework": "CIS", "name_en": "CloudTrail integrated with CloudWatch Logs",              "name_es": "CloudTrail integrado con CloudWatch Logs"},
    {"control_id": "CIS-CT-3.1-MR", "service": "cloudwatch", "framework": "CIS", "name_en": "CloudTrail multi-region trail enabled",                  "name_es": "Trail multi-región de CloudTrail habilitado"},
    {"control_id": "CIS-CT-3.2",    "service": "cloudwatch", "framework": "CIS", "name_en": "CloudTrail log file validation enabled",                 "name_es": "Validación de archivos de log de CloudTrail habilitada"},
    {"control_id": "CIS-CT-3.7",    "service": "cloudwatch", "framework": "CIS", "name_en": "CloudTrail logs encrypted with KMS",                    "name_es": "Logs de CloudTrail encriptados con KMS"},
    {"control_id": "CIS-CW-4.1",    "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.1 — Root account usage alarm",                    "name_es": "CIS 4.1 — Alarma de uso de cuenta root"},
    {"control_id": "CIS-CW-4.2",    "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.2 — Console login without MFA alarm",             "name_es": "CIS 4.2 — Alarma de login sin MFA"},
    {"control_id": "CIS-CW-4.3",    "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.3 — IAM policy changes alarm",                    "name_es": "CIS 4.3 — Alarma de cambios en políticas IAM"},
    {"control_id": "CIS-CW-4.4",    "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.4 — CloudTrail configuration changes alarm",      "name_es": "CIS 4.4 — Alarma de cambios en CloudTrail"},
    {"control_id": "CIS-CW-4.5",    "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.5 — Console login failures alarm",                "name_es": "CIS 4.5 — Alarma de fallos de login en consola"},
    {"control_id": "CIS-CW-4.6",    "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.6 — Disabled CMK usage alarm",                   "name_es": "CIS 4.6 — Alarma de uso de CMK deshabilitada"},
    {"control_id": "CIS-CW-4.7",    "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.7 — S3 bucket policy changes alarm",             "name_es": "CIS 4.7 — Alarma de cambios en políticas S3"},
    {"control_id": "CIS-CW-4.8",    "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.8 — AWS Config changes alarm",                   "name_es": "CIS 4.8 — Alarma de cambios en AWS Config"},
    {"control_id": "CIS-CW-4.9",    "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.9 — Security group changes alarm",               "name_es": "CIS 4.9 — Alarma de cambios en security groups"},
    {"control_id": "CIS-CW-4.10",   "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.10 — NACL changes alarm",                       "name_es": "CIS 4.10 — Alarma de cambios en NACLs"},
    {"control_id": "CIS-CW-4.11",   "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.11 — Network gateway changes alarm",             "name_es": "CIS 4.11 — Alarma de cambios en gateways de red"},
    {"control_id": "CIS-CW-4.12",   "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.12 — Route table changes alarm",                 "name_es": "CIS 4.12 — Alarma de cambios en route tables"},
    {"control_id": "CIS-CW-4.13",   "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.13 — VPC changes alarm",                        "name_es": "CIS 4.13 — Alarma de cambios en VPCs"},
    {"control_id": "CIS-CW-4.14",   "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.14 — AWS Organizations changes alarm",           "name_es": "CIS 4.14 — Alarma de cambios en AWS Organizations"},
    {"control_id": "CIS-CW-4.15",   "service": "cloudwatch", "framework": "CIS", "name_en": "CIS 4.15 — AWS Config configuration changes alarm",    "name_es": "CIS 4.15 — Alarma de cambios en configuración de AWS Config"},
    {"control_id": "WAF-CW-LG-01",  "service": "cloudwatch", "framework": "WAF", "name_en": "CloudWatch Log Groups have retention policy",          "name_es": "Log Groups de CloudWatch con política de retención"},
    {"control_id": "WAF-CW-LG-02",  "service": "cloudwatch", "framework": "WAF", "name_en": "CloudWatch Log Groups encrypted with KMS",             "name_es": "Log Groups de CloudWatch encriptados con KMS"},
    {"control_id": "WAF-CW-ALM-01", "service": "cloudwatch", "framework": "WAF", "name_en": "CloudWatch alarms have notification actions",          "name_es": "Alarmas de CloudWatch con acciones de notificación"},
    {"control_id": "WAF-CW-ALM-02", "service": "cloudwatch", "framework": "WAF", "name_en": "CloudWatch alarms not in ALARM state",                "name_es": "Alarmas de CloudWatch no en estado ALARM"},
    {"control_id": "WAF-CW-ALM-03", "service": "cloudwatch", "framework": "WAF", "name_en": "CloudWatch alarms not in INSUFFICIENT_DATA state",    "name_es": "Alarmas de CloudWatch no en estado INSUFFICIENT_DATA"},
    # ── VPC ───────────────────────────────────────────────────────────────────
    {"control_id": "CIS-VPC-3.9",    "service": "vpc", "framework": "CIS", "name_en": "VPC Flow Logs enabled",                                "name_es": "VPC Flow Logs habilitados"},
    {"control_id": "WAF-VPC-FL-01",  "service": "vpc", "framework": "WAF", "name_en": "VPC Flow Logs capture ALL traffic",                   "name_es": "VPC Flow Logs capturan tráfico ALL"},
    {"control_id": "WAF-VPC-FL-02",  "service": "vpc", "framework": "WAF", "name_en": "VPC Flow Logs destination is configured correctly",   "name_es": "Destino de VPC Flow Logs correctamente configurado"},
    {"control_id": "CIS-VPC-5.3",    "service": "vpc", "framework": "CIS", "name_en": "Default VPC not in use for workloads",               "name_es": "VPC default no usada para workloads"},
    {"control_id": "WAF-VPC-CID-01", "service": "vpc", "framework": "WAF", "name_en": "VPC CIDR blocks do not overlap",                     "name_es": "CIDRs de VPCs no se solapan"},
    {"control_id": "WAF-VPC-PER-01", "service": "vpc", "framework": "WAF", "name_en": "VPC peering cross-account connections reviewed",     "name_es": "Peerings VPC cross-account revisados"},
    {"control_id": "WAF-VPC-PER-02", "service": "vpc", "framework": "WAF", "name_en": "VPC peering cross-region connections reviewed",     "name_es": "Peerings VPC cross-region revisados"},
    {"control_id": "WAF-VPC-EPO-01", "service": "vpc", "framework": "WAF", "name_en": "VPC Endpoint policies are not open",                "name_es": "Políticas de VPC Endpoints no abiertas"},
    {"control_id": "WAF-VPC-EPM-01", "service": "vpc", "framework": "WAF", "name_en": "Critical services have VPC Endpoints",             "name_es": "Servicios críticos con VPC Endpoints"},
    {"control_id": "WAF-VPC-DNS-01", "service": "vpc", "framework": "WAF", "name_en": "DHCP option sets use trusted DNS servers",         "name_es": "DHCP option sets con DNS servers de confianza"},
    {"control_id": "WAF-VPC-VPN-01", "service": "vpc", "framework": "WAF", "name_en": "VPN connection tunnels are UP",                    "name_es": "Túneles VPN en estado UP"},
    {"control_id": "WAF-VPC-PL-01",  "service": "vpc", "framework": "WAF", "name_en": "PrivateLink services require acceptance",          "name_es": "Servicios PrivateLink requieren aceptación manual"},
    {"control_id": "WAF-VPC-R53-01", "service": "vpc", "framework": "WAF", "name_en": "Route 53 Resolver rules share status reviewed",   "name_es": "Estado de compartición de reglas Resolver revisado"},
]

# Total de controles en el catálogo
TOTAL_CONTROLS = len(CONTROLS_CATALOG)

# Índice rápido por control_id
CONTROLS_BY_ID = {c["control_id"]: c for c in CONTROLS_CATALOG}